"""Initial migration

Revision ID: d75f61645f75
Revises: 
Create Date: 2024-09-28 12:43:22.489742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75f61645f75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_data', schema=None) as batch_op:
        batch_op.create_index('idx_session_data_type', ['session_id', 'data_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_data_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_data_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_data_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_data_user_id'))
        batch_op.drop_index(batch_op.f('ix_survey_data_timestamp'))
        batch_op.drop_index(batch_op.f('ix_survey_data_session_id'))
        batch_op.drop_index('idx_session_data_type')

    op.drop_table('survey_data')
    # ### end Alembic commands ###
